name: Lint more Commit Messages
on: ['push']

jobs:
  lint:
    runs-on: ubuntu-latest
    name: conventional
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v3
