name: reviewdog-suggester

on: [pull_request] # Support only pull_request event.

jobs:
  aritest:
    name: aritest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, intl, iconv
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: suggester / lint
      - uses: reviewdog/action-setup@v1
        run: ./vendor/bin/php-cs-fixer fix --dry-run --using-cache false --diff --diff-format udiff | reviewdog -name="aritest3" -reporter=github-pr-check

      - name: suggester / psalm
        run: ./vendor/bin/psalm --output-format=text | reviewdog -name="aritest" -reporter=github-pr-check
